namespace MarcasAutos.Models
{
    /// <summary>
    /// Represents a car brand stored in the database.
    /// </summary>
    public class MarcaAuto
    {
        /// <summary>Primary key — auto-generated by the database.</summary>
        public int Id { get; set; }
        /// <summary>Brand name, e.g. "Toyota", "Ford", "BMW".</summary>
        public string Name { get; set; } = string.Empty;
        /// <summary>Country of origin for the brand.</summary>
        public string Country { get; set; } = string.Empty;
        /// <summary>Year the brand was founded.</summary>
        public int Year { get; set; }
    }
}
