services:
  marcasautos.api:
    image: ${DOCKER_REGISTRY-}marcasautos
    container_name: marcasautos.api
    build:
      context: .
      dockerfile: MarcasAutos/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

      
  marcasautos.db:
    image: postgres:latest
    container_name: marcasautos.db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    volumes:
      - ./.containers/postgres/data:/var/lib/postgresql
    ports:
      - "5433:5432"



    
