Remove-Item -Path "C:\Users\Elavon dev\Desktop\MarcasAutos\MarcasAutos.Tests\TestResults" -Recurse -Force -ErrorAction SilentlyContinue

dotnet test "C:\Users\Elavon dev\Desktop\MarcasAutos\MarcasAutos.Tests\MarcasAutos.Tests.csproj" --collect:"XPlat Code Coverage"

reportgenerator -reports:"C:\Users\Elavon dev\Desktop\MarcasAutos\MarcasAutos.Tests\TestResults\**\coverage.cobertura.xml" -targetdir:"C:\Users\Elavon dev\Desktop\MarcasAutos\coveragereport" -reporttypes:Html -classfilters:"-MarcasAutos.Migrations.*;-Microsoft.AspNetCore.OpenApi.Generated.*;-AutoGeneratedProgram;-Program" -filefilters:"-**/Migrations/**;-**/obj/**;-**/Program.cs"

start "C:\Users\Elavon dev\Desktop\MarcasAutos\coveragereport\index.html"